name: CI / App

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'app/**'
      - 'docker-compose.yml'
      - '.github/workflows/ci.yml'

env:
  node_version: "22.x"
  FORCE_COLOR: 3

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        working-directory: app
        run: npm ci --prefer-offline

#      - name: npm test
#        working-directory: src
#        run: npm test
#
      - name: npm run build
        working-directory: app
        run: npm run build

#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    timeout-minutes: 3
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: ${{ env.node_version }}
#          cache: npm
#          cache-dependency-path: '**/package-lock.json'
#
#      - name: npm ci
#        working-directory: src
#        run: npm ci --prefer-offline
#
#      - name: npm lint
#        working-directory: src
#        run: npm run lint
#
#  docker:
#    name: Docker Build
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: docker build
#        uses: docker/build-push-action@v6
#        with:
#          context: src
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
