name: Publish 'chill389cc/devsite'

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

env:
  node_version: "22.x"
  release_version: "v1.0.0"
  FORCE_COLOR: 3

jobs:
  build:
    name: Build & Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        working-directory: app
        run: npm ci --prefer-offline

      - name: npm run build
        working-directory: app
        run: npm run build

  build_and_deploy:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: $release_version
      url: https://google.com
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chill389cc/devsite
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: chill389cc/devsite:${{ env.release_version }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print new version
        run: echo "version=chill389cc/devsite:${{ env.release_version }}" >> $GITHUB_OUTPUT
